services:
  # SERVICE 1: Your Notebook Environment
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    container_name: capstone-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
      - /workspace/.venv
      - ./data:/workspace/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - KAGGLE_CONFIG_DIR=/workspace
    restart: unless-stopped

  # SERVICE 2: Prod Prediction API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone-api
    ports:
      - "9696:9696"
    environment:
      - PORT=9696